# Popup setup for Git/GitHub local env.
# Double-click or run:
#   powershell -ExecutionPolicy Bypass -File .\scripts\setup-git-env.ps1
#
# Writes scripts/git-env.local.ps1 (gitignored), then closes.

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$localEnv = Join-Path $scriptDir "git-env.local.ps1"

$existingToken = ""
$existingName = "smiliy"
$existingEmail = "wangzikai2000@163.com"
$existingRemote = "https://github.com/dsmiling/DrawPaint.git"

if (Test-Path $localEnv) {
    $raw = Get-Content -Raw -Path $localEnv
    if ($raw -match '\$env:GH_TOKEN\s*=\s*"([^"]*)"') { $existingToken = $Matches[1] }
    if ($raw -match '\$env:GIT_AUTHOR_NAME\s*=\s*"([^"]*)"') { $existingName = $Matches[1] }
    if ($raw -match '\$env:GIT_AUTHOR_EMAIL\s*=\s*"([^"]*)"') { $existingEmail = $Matches[1] }
    if ($raw -match '\$env:DRAWPAINT_GIT_REMOTE\s*=\s*"([^"]*)"') { $existingRemote = $Matches[1] }
}

$form = New-Object System.Windows.Forms.Form
$form.Text = "DrawPaint Git Env Setup"
$form.Size = New-Object System.Drawing.Size(520, 320)
$form.StartPosition = "CenterScreen"
$form.FormBorderStyle = "FixedDialog"
$form.MaximizeBox = $false
$form.MinimizeBox = $false
$form.TopMost = $true

function Add-LabeledTextBox {
    param(
        [string]$Label,
        [int]$Y,
        [string]$Value,
        [bool]$Password = $false,
        [int]$Height = 24
    )
    $lbl = New-Object System.Windows.Forms.Label
    $lbl.Text = $Label
    $lbl.Location = New-Object System.Drawing.Point(20, $Y)
    $lbl.Size = New-Object System.Drawing.Size(460, 18)
    $form.Controls.Add($lbl)

    $box = New-Object System.Windows.Forms.TextBox
    $box.Location = New-Object System.Drawing.Point(20, ($Y + 20))
    $box.Size = New-Object System.Drawing.Size(460, $Height)
    $box.Text = $Value
    if ($Password) { $box.UseSystemPasswordChar = $true }
    $form.Controls.Add($box)
    return $box
}

$tokenBox = Add-LabeledTextBox -Label "GitHub Token (ghp_ / github_pat_)" -Y 16 -Value $existingToken -Password $true
$nameBox = Add-LabeledTextBox -Label "Git Author Name" -Y 72 -Value $existingName
$emailBox = Add-LabeledTextBox -Label "Git Author Email" -Y 128 -Value $existingEmail
$remoteBox = Add-LabeledTextBox -Label "Remote (optional)" -Y 184 -Value $existingRemote

$okBtn = New-Object System.Windows.Forms.Button
$okBtn.Text = "Save & Close"
$okBtn.Location = New-Object System.Drawing.Point(280, 240)
$okBtn.Size = New-Object System.Drawing.Size(110, 30)
$form.Controls.Add($okBtn)

$cancelBtn = New-Object System.Windows.Forms.Button
$cancelBtn.Text = "Cancel"
$cancelBtn.Location = New-Object System.Drawing.Point(400, 240)
$cancelBtn.Size = New-Object System.Drawing.Size(80, 30)
$cancelBtn.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.Controls.Add($cancelBtn)
$form.CancelButton = $cancelBtn

$okBtn.Add_Click({
    $token = $tokenBox.Text.Trim()
    $name = $nameBox.Text.Trim()
    $email = $emailBox.Text.Trim()
    $remote = $remoteBox.Text.Trim()

    if ([string]::IsNullOrWhiteSpace($token)) {
        [System.Windows.Forms.MessageBox]::Show("Please enter a GitHub Token.", "Missing Token", "OK", "Warning") | Out-Null
        return
    }
    if ([string]::IsNullOrWhiteSpace($name) -or [string]::IsNullOrWhiteSpace($email)) {
        [System.Windows.Forms.MessageBox]::Show("Please fill Author Name and Email.", "Missing Info", "OK", "Warning") | Out-Null
        return
    }

    $remoteLine = if ($remote) {
        "`$env:DRAWPAINT_GIT_REMOTE = `"$remote`""
    } else {
        "# `$env:DRAWPAINT_GIT_REMOTE = `"https://github.com/OWNER/DrawPaint.git`""
    }

    $content = @"
# Generated by scripts/setup-git-env.ps1 — gitignored, do not commit.

`$env:GH_TOKEN = "$token"
`$env:GITHUB_TOKEN = `$env:GH_TOKEN

`$env:GIT_AUTHOR_NAME = "$name"
`$env:GIT_AUTHOR_EMAIL = "$email"
`$env:GIT_COMMITTER_NAME = `$env:GIT_AUTHOR_NAME
`$env:GIT_COMMITTER_EMAIL = `$env:GIT_AUTHOR_EMAIL

$remoteLine
"@

    Set-Content -Path $localEnv -Value $content -Encoding UTF8

    $env:GH_TOKEN = $token
    $env:GITHUB_TOKEN = $token
    $env:GIT_AUTHOR_NAME = $name
    $env:GIT_AUTHOR_EMAIL = $email
    $env:GIT_COMMITTER_NAME = $name
    $env:GIT_COMMITTER_EMAIL = $email
    if ($remote) { $env:DRAWPAINT_GIT_REMOTE = $remote }

    $msg = "Saved to:`n$localEnv`n`nThen run in terminal:`n. .\scripts\set-git-env.ps1"
    [System.Windows.Forms.MessageBox]::Show($msg, "Done", "OK", "Information") | Out-Null

    $form.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.Close()
})

[void]$form.ShowDialog()
$form.Dispose()
